services:
  book-mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookmanagement
      MYSQL_USER: Tommy
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 20s
      timeout: 20s
      retries: 5
  beer-mongo:
    image: tommyrabes/beer-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh beer-mongo:27017/admin --quiet -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 5
  oauth2-authorization-server:
    image: tommyrabes/spring-authorization-server
    ports:
      - 9000:9000
  spring-boot-webapp:
    image: tommyrabes/spring-boot-webapp
    ports:
      - 8083:8083
    depends_on:
      book-mysql:
        condition: service_healthy
      oauth2-authorization-server:
        condition: service_started
  spring-6-reactive-app:
    image: tommyrabes/spring-6-reactive-app
    ports:
      - 8082:8082
    depends_on:
      beer-mongo:
        condition: service_healthy
      oauth2-authorization-server:
        condition: service_started
  spring-6-cloud-gateway:
    image: tommyrabes/spring-6-cloud-gateway
    ports:
      - 8080:8080
    depends_on:
      - oauth2-authorization-server
      - spring-boot-webapp
      - spring-6-reactive-app