spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: spring-boot-webapp
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/*
        - id: spring-6-reactive-app
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/*,/api/v3/*  # Syntax based on PathMatcher
#      httpserver:
#        # Allows to see the information that are sent back and forth
#        wiretap: true
#      httpclient:
#        wiretap: true
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: trace
