apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: beer-mongo
  name: beer-mongo
spec:
  ports:
  - name: 27017-27017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: beer-mongo
  type: ClusterIP
status:
  loadBalancer: {}
